version: '3.7'

networks:
  blasting:
    driver: macvlan
    driver_opts:
      parent: ${BLASTING_INTERFACE}
    ipam:
      config:
        - subnet: 192.168.128.0/24

services:
  dhcp:
    build: dhcp/
    image: dhcp
    network_mode: host
    restart: always
  tftp.bios:
    build: tftp/
    image: tftp
    privileged: true
    ports:
      - "69:69"
    volumes:
      - ./tftpboot.bios:/var/lib/tftpboot
    networks:
      blasting:
        ipv4_address: 192.168.128.3
    restart: always
  tftp.uefi:
    build: tftp/
    image: tftp
    privileged: true
    ports:
      - "69:69"
    volumes:
      - ./tftpboot.uefi:/var/lib/tftpboot
    networks:
      blasting:
        ipv4_address: 192.168.128.4
    restart: always
  webapp:
    build: webapp/
    image: webapp
    privileged: true
    network_mode: host
    volumes:
      - ./tftpboot.bios:/opt/tftpboot.bios
      - ./tftpboot.uefi:/opt/tftpboot.uefi
      - ./instance:/opt/instance
      - ./instance/exports:/etc/exports
      - ./images:/opt/images
      - ./scripts:/opt/scripts
    restart: always
